name: Json

on:
  schedule:
    - cron: "*/30 * * * *"
  push: 
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name : Rm old
        run : | 
          rm *.json

      - name: Grant execute permission for script
        run: chmod +x pif.sh

      - name: Generate JSON file
        run: ./pif.sh

      - name: Replace old JSON files with new ones
        run: |
          git config --global user.name "daboynb"
          git config --global user.email "username@users.noreply.github.com"
          git add chiteroman.json
          git add osmosis.json
          git commit -m "Update pif.json"
          git push
